server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      routes:
        - id: agendamento-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/cadastro/**, /api/pesquisa/**, /api/admin/**
          
        - id: clinica-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/clinica/**
          
        - id: centro-cirurgico-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/procedimentos/**
      
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/hospital
